# Analyzing Employment Data from SCB

This script utilizes the SCB API to retrieve and analyze employment data for the population aged 15-74 years. It focuses on individuals classified as 'sysselsatta' (employed) and 'sysselsatta i arbete' (employed at work) for the years 2000 to 2020. The extracted data is then cleaned, formatted, and saved to an Excel file named 'employment.xlsx'. The script uses the PySCBWrapper, NumPy, and Pandas libraries.

In [1]:
# Import necessary libraries

from pyscbwrapper import SCB
import numpy as np
import pandas as pd

In [2]:
# Initialize SCB object for Swedish data
scb = SCB('sv')
scb.info()

[{'id': 'AA', 'type': 'l', 'text': 'Ämnesövergripande statistik'},
 {'id': 'AM', 'type': 'l', 'text': 'Arbetsmarknad'},
 {'id': 'BE', 'type': 'l', 'text': 'Befolkning'},
 {'id': 'BO', 'type': 'l', 'text': 'Boende, byggande och bebyggelse'},
 {'id': 'EN', 'type': 'l', 'text': 'Energi'},
 {'id': 'FM', 'type': 'l', 'text': 'Finansmarknad'},
 {'id': 'HA', 'type': 'l', 'text': 'Handel med varor och tjänster'},
 {'id': 'HE', 'type': 'l', 'text': 'Hushållens ekonomi'},
 {'id': 'HS', 'type': 'l', 'text': 'Hälso- och sjukvård'},
 {'id': 'JO', 'type': 'l', 'text': 'Jord- och skogsbruk, fiske'},
 {'id': 'KU', 'type': 'l', 'text': 'Kultur och fritid'},
 {'id': 'LE', 'type': 'l', 'text': 'Levnadsförhållanden'},
 {'id': 'ME', 'type': 'l', 'text': 'Demokrati'},
 {'id': 'MI', 'type': 'l', 'text': 'Miljö'},
 {'id': 'NR', 'type': 'l', 'text': 'Nationalräkenskaper'},
 {'id': 'NV', 'type': 'l', 'text': 'Näringsverksamhet'},
 {'id': 'OE', 'type': 'l', 'text': 'Offentlig ekonomi'},
 {'id': 'PR', 'type': 'l', 'text': 'Priser och konsumtion'},
 {'id': 'SO', 'type': 'l', 'text': 'Socialtjänst'},
 {'id': 'TK', 'type': 'l', 'text': 'Transporter och kommunikationer'},
 {'id': 'UF', 'type': 'l', 'text': 'Utbildning och forskning'}]

In [3]:
# Navigate to the desired data level using codes
scb.go_down('AM')
scb.info()

[{'id': 'AM0301',
  'type': 'l',
  'text': 'Arbetskostnadsindex för arbetare och tjänstemän inom privat sektor (AKI)'},
 {'id': 'AM0401', 'type': 'l', 'text': 'Arbetskraftsundersökningarna (AKU)'},
 {'id': 'AM0403',
  'type': 'l',
  'text': 'Arbetskraftsundersökningarna, tidigare definitioner'},
 {'id': 'AM0402',
  'type': 'l',
  'text': 'Arbetskraftsundersökningar, äldre serier (AKU)'},
 {'id': 'AM0501', 'type': 'l', 'text': 'Arbetsmiljöundersökningen'},
 {'id': 'AM0502', 'type': 'l', 'text': 'Arbetsorsakade besvär'},
 {'id': 'AM0210',
  'type': 'l',
  'text': 'Befolkningens arbetsmarknadsstatus (BAS)'},
 {'id': 'AM0209',
  'type': 'l',
  'text': 'Konjunkturstatistik över sjuklöner (KSju)'},
 {'id': 'AM0701',
  'type': 'l',
  'text': 'Konjunkturstatistik över vakanser (KV)'},
 {'id': 'AM0108',
  'type': 'l',
  'text': 'Konjunkturstatistik, löner för kommuner (KLK)'},
 {'id': 'AM0109',
  'type': 'l',
  'text': 'Konjunkturstatistik, löner för regioner (KLR)'},
 {'id': 'AM0101',
  'type': 'l',
  'text': 'Konjunkturstatistik, löner för privat sektor (KLP)'},
 {'id': 'AM0102',
  'type': 'l',
  'text': 'Konjunkturstatistik, löner för statlig sektor (KLS)'},
 {'id': 'AM0302',
  'type': 'l',
  'text': 'Registerbaserad lönesummestatistik (LSUM)'},
 {'id': 'AM0201',
  'type': 'l',
  'text': 'Kortperiodisk sysselsättningsstatistik (KS)'},
 {'id': 'AM0114', 'type': 'l', 'text': 'Labour cost index'},
 {'id': 'AM0107',
  'type': 'l',
  'text': 'Löner och sysselsättning inom kyrko-kommunal sektor'},
 {'id': 'AM0110', 'type': 'l', 'text': 'Lönestrukturstatistik, hela ekonomin'},
 {'id': 'AM0105', 'type': 'l', 'text': 'Lönestrukturstatistik, regioner'},
 {'id': 'AM0106', 'type': 'l', 'text': 'Lönestrukturstatistik, kommuner'},
 {'id': 'AM0103',
  'type': 'l',
  'text': 'Lönestrukturstatistik, privat sektor (SLP)'},
 {'id': 'AM0104',
  'type': 'l',
  'text': 'Lönestrukturstatistik, statlig sektor'},
 {'id': 'AM0206',
  'type': 'l',
  'text': 'Lönesummor, arbetsgivaravgifter och preliminär A-skatt (LAPS)'},
 {'id': 'AM9906', 'type': 'l', 'text': 'Regionala matchningsindikatorer'},
 {'id': 'AM0207',
  'type': 'l',
  'text': 'Registerbaserad arbetsmarknadsstatistik (RAMS)'},
 {'id': 'AM0208', 'type': 'l', 'text': 'Yrkesregistret med yrkesstatistik'}]

In [4]:
scb.go_down('AM0403')
scb.info()

[{'id': 'AM0403A',
  'type': 'l',
  'text': 'Befolkningen efter arbetskraftstillhörighet 1970-2020'},
 {'id': 'AM0403I', 'type': 'l', 'text': 'Sysselsatta 1970-2020'},
 {'id': 'AM0403J', 'type': 'l', 'text': 'Anställda 2005-2020'},
 {'id': 'AM0403S', 'type': 'l', 'text': 'Arbetstid 2005-2020'},
 {'id': 'AM0403B',
  'type': 'l',
  'text': 'Arbetstid efter näringsgren (SNI2007) 2009-2020'},
 {'id': 'AM0403K', 'type': 'l', 'text': 'Frånvarande 2005-2020'},
 {'id': 'AM0403L', 'type': 'l', 'text': 'Arbetslösa 2005-2020'},
 {'id': 'AM0403M',
  'type': 'l',
  'text': 'Personer ej i arbetskraften 2005-2020'},
 {'id': 'AM0403O',
  'type': 'l',
  'text': 'Outnyttjat arbetskraftsutbud 2005-2020'},
 {'id': 'AM0403N', 'type': 'l', 'text': 'Regionala tabeller 2005-2020'},
 {'id': 'AM0403P',
  'type': 'l',
  'text': 'Utbildningens nivå och inriktning 2005-2020'},
 {'id': 'AM0403Q', 'type': 'l', 'text': 'Civilstånd och barn 2005-2020'},
 {'id': 'AM0403R', 'type': 'l', 'text': 'Inrikes och utrikes födda 2005-2020'},
 {'id': 'AM0403U',
  'type': 'l',
  'text': 'Unga som varken arbetar eller studerar (NEET) 2007-2020'},
 {'id': 'AM0403C',
  'type': 'l',
  'text': 'Arbetstid efter näringsgren (SNI2002) 2005-2008'}]

In [5]:
scb.go_down('AM0403I')
scb.info()

[{'id': 'NAKUSysselsatta2MTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU), därav i arbete samt därav frånvarande hela veckan efter kön och ålder, tidigare definitioner. Månad 1970M01 - 2020M12',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselsatta2KTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU), därav i arbete samt därav frånvarande hela veckan efter kön och ålder, tidigare definitioner.  Kvartal 1970K1 - 2020K4',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselsatta2ArTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU), därav i arbete samt därav frånvarande hela veckan efter kön och ålder, tidigare definitioner.  År 1970 - 2020',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselAnk2MTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, kön och ålder, tidigare definitioner.  Månad 1970M01 - 2020M12',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselAnk2KTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, kön och ålder, tidigare definitioner.  Kvartal 1970K1 - 2020K4',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselAnk2ArTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, kön och ålder, tidigare definitioner. År 1970 - 2020',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselSNI07MTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, näringsgren SNI2007 och kön, tidigare definitioner. Månad 2009M01 - 2020M12',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselSNI07KTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, näringsgren SNI2007 och kön, tidigare definitioner. Kvartal 2009K1 - 2020K4',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselSNI07ArTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, näringsgren SNI2007 och kön, tidigare definitioner. År 2009 - 2020',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselYrke12MTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, yrke SSYK 2012 och kön, tidigare definitioner. Månad 2015M01 - 2020M12',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselYrke12KTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, yrke SSYK 2012 och kön, tidigare definitioner. Kvartal 2015K1 - 2020K4',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselYrke12ArTD',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, yrke SSYK 2012 och kön, tidigare definitioner. År 2015 - 2020',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSyssStudHDMTD',
  'type': 't',
  'text': 'Sysselsatta som studerar 15-74 år (AKU) efter hel/deltidsstudier, kön och ålder, tidigare definitioner. Månad 2005M04 - 2020M12',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSyssStudHDKTD',
  'type': 't',
  'text': 'Sysselsatta som studerar 15-74 år (AKU) efter hel/deltidsstudier, kön och ålder, tidigare definitioner. Kvartal 2005K2 - 2020K4',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSyssStudHDArTD',
  'type': 't',
  'text': 'Sysselsatta som studerar 15-74 år (AKU) efter hel/deltidsstudier, kön och ålder, tidigare definitioner. År 2005 - 2020',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUStudArbSnittTMTD',
  'type': 't',
  'text': 'Sysselsatta som studerar 15-74 år (AKU) - genomsnittligt antal arbets-/studietimmar per vecka samt antal sysselsatta efter kön och ålder, tidigare definitioner. Månad 2005M04 - 2020M12',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUStudArbSnittTKTD',
  'type': 't',
  'text': 'Sysselsatta som studerar 15-74 år (AKU) - genomsnittligt antal arbets-/studietimmar per vecka samt antal sysselsatta efter kön och ålder, tidigare definitioner. Kvartal 2005K2 - 2020K4',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUStudArbSnittTATD',
  'type': 't',
  'text': 'Sysselsatta som studerar 15-74 år (AKU) - genomsnittligt antal arbets-/studietimmar per vecka samt antal sysselsatta efter kön och ålder, tidigare definitioner. År 2005 - 2020',
  'updated': '2022-02-18T08:00:00'},
 {'id': 'NAKUSysselSNIM',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, näringsgren SNI2002 och kön. Månad 2005M04 - 2008M12',
  'updated': '2009-01-22T09:33:00'},
 {'id': 'NAKUSysselSNIK',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, näringsgren SNI2002 och kön. Kvartal 2005K2 - 2008K4',
  'updated': '2009-01-22T09:36:00'},
 {'id': 'NAKUSysselSNIAr',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, näringsgren SNI2002 och kön. År 2005 - 2008',
  'updated': '2009-01-29T09:33:00'},
 {'id': 'NAKUSysselYrkeM',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, yrke SSYK 96 och kön. Månad 2005M04 - 2015M12',
  'updated': '2016-01-28T09:30:00'},
 {'id': 'NAKUSysselYrkeK',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, yrke SSYK 96 och kön. Kvartal 2005K2 - 2015K4',
  'updated': '2016-01-28T09:30:00'},
 {'id': 'NAKUSysselYrkeAr',
  'type': 't',
  'text': 'Sysselsatta 15-74 år (AKU) efter anknytningsgrad till arbetsmarknaden, yrke SSYK 96 och kön. År 2005 - 2015',
  'updated': '2016-01-28T09:30:00'}]

In [6]:
scb.go_down('NAKUSysselsatta2MTD')
scb.info()

{'title': 'Tidigare definitioner. Sysselsatta 15-74 år (AKU) efter kön, ålder, arbetskraftstillhörighet, tabellinnehåll och månad',
 'variables': [{'code': 'Kon',
   'text': 'kön',
   'values': ['1', '2', '1+2'],
   'valueTexts': ['män', 'kvinnor', 'totalt'],
   'elimination': True},
  {'code': 'Alder',
   'text': 'ålder',
   'values': ['15-19',
    '15-24',
    '20-24',
    '25-34',
    '35-44',
    '45-54',
    '55-64',
    '65-74',
    'tot15-74',
    'tot16-64',
    'tot16-65',
    'tot16-66',
    'tot20-64',
    'tot20-65',
    'tot20-66'],
   'valueTexts': ['15-19 år',
    '15-24 år',
    '20-24 år',
    '25-34 år',
    '35-44 år',
    '45-54 år',
    '55-64 år',
    '65-74 år',
    'totalt 15-74 år',
    'totalt 16-64 år',
    'totalt 16-65 år',
    'totalt 16-66 år',
    'totalt 20-64 år',
    'totalt 20-65 år',
    'totalt 20-66 år'],
   'elimination': True},
  {'code': 'Arbetskraftstillh',
   'text': 'arbetskraftstillhörighet',
   'values': ['SYS', 'IARBAVSYSS', 'FRANVHVAVSYSS'],
   'valueTexts': ['sysselsatta',
    'sysselsatta i arbete',
    'sysselsatta frånvarande hela veckan'],
   'elimination': True},
  {'code': 'ContentsCode',
   'text': 'tabellinnehåll',
   'values': ['00000648', '00000647'],
   'valueTexts': ['1000-tal', 'Felmarginal ±, 1000-tal']},
  {'code': 'Tid',
   'text': 'månad',
   'values': ['1970M01',
    '1970M02',
    '1970M03',
    '1970M04',
    '1970M05',
    '1970M06',
    '1970M07',
    '1970M08',
    '1970M09',
    '1970M10',
    '1970M11',
    '1970M12',
    '1971M01',
    '1971M02',
    '1971M03',
    '1971M04',
    '1971M05',
    '1971M06',
    '1971M07',
    '1971M08',
    '1971M09',
    '1971M10',
    '1971M11',
    '1971M12',
    '1972M01',
    '1972M02',
    '1972M03',
    '1972M04',
    '1972M05',
    '1972M06',
    '1972M07',
    '1972M08',
    '1972M09',
    '1972M10',
    '1972M11',
    '1972M12',
    '1973M01',
    '1973M02',
    '1973M03',
    '1973M04',
    '1973M05',
    '1973M06',
    '1973M07',
    '1973M08',
    '1973M09',
    '1973M10',
    '1973M11',
    '1973M12',
    '1974M01',
    '1974M02',
    '1974M03',
    '1974M04',
    '1974M05',
    '1974M06',
    '1974M07',
    '1974M08',
    '1974M09',
    '1974M10',
    '1974M11',
    '1974M12',
    '1975M01',
    '1975M02',
    '1975M03',
    '1975M04',
    '1975M05',
    '1975M06',
    '1975M07',
    '1975M08',
    '1975M09',
    '1975M10',
    '1975M11',
    '1975M12',
    '1976M01',
    '1976M02',
    '1976M03',
    '1976M04',
    '1976M05',
    '1976M06',
    '1976M07',
    '1976M08',
    '1976M09',
    '1976M10',
    '1976M11',
    '1976M12',
    '1977M01',
    '1977M02',
    '1977M03',
    '1977M04',
    '1977M05',
    '1977M06',
    '1977M07',
    '1977M08',
    '1977M09',
    '1977M10',
    '1977M11',
    '1977M12',
    '1978M01',
    '1978M02',
    '1978M03',
    '1978M04',
    '1978M05',
    '1978M06',
    '1978M07',
    '1978M08',
    '1978M09',
    '1978M10',
    '1978M11',
    '1978M12',
    '1979M01',
    '1979M02',
    '1979M03',
    '1979M04',
    '1979M05',
    '1979M06',
    '1979M07',
    '1979M08',
    '1979M09',
    '1979M10',
    '1979M11',
    '1979M12',
    '1980M01',
    '1980M02',
    '1980M03',
    '1980M04',
    '1980M05',
    '1980M06',
    '1980M07',
    '1980M08',
    '1980M09',
    '1980M10',
    '1980M11',
    '1980M12',
    '1981M01',
    '1981M02',
    '1981M03',
    '1981M04',
    '1981M05',
    '1981M06',
    '1981M07',
    '1981M08',
    '1981M09',
    '1981M10',
    '1981M11',
    '1981M12',
    '1982M01',
    '1982M02',
    '1982M03',
    '1982M04',
    '1982M05',
    '1982M06',
    '1982M07',
    '1982M08',
    '1982M09',
    '1982M10',
    '1982M11',
    '1982M12',
    '1983M01',
    '1983M02',
    '1983M03',
    '1983M04',
    '1983M05',
    '1983M06',
    '1983M07',
    '1983M08',
    '1983M09',
    '1983M10',
    '1983M11',
    '1983M12',
    '1984M01',
    '1984M02',
    '1984M03',
    '1984M04',
    '1984M05',
    '1984M06',
    '1984M07',
    '1984M08',
    '1984M09',
    '1984M10',
    '1984M11',
    '1984M12',
    '1985M01',
    '1985M02',
    '1985M03',
    '1985M04',
    '1985M05',
    '1985M06',
    '1985M07',
    '1985M08',
    '1985M09',
    '1985M10',
    '1985M11',
    '1985M12',
    '1986M01',
    '1986M02',
    '1986M03',
    '1986M04',
    '1986M05',
    '1986M06',
    '1986M07',
    '1986M08',
    '1986M09',
    '1986M10',
    '1986M11',
    '1986M12',
    '1987M01',
    '1987M02',
    '1987M03',
    '1987M04',
    '1987M05',
    '1987M06',
    '1987M07',
    '1987M08',
    '1987M09',
    '1987M10',
    '1987M11',
    '1987M12',
    '1988M01',
    '1988M02',
    '1988M03',
    '1988M04',
    '1988M05',
    '1988M06',
    '1988M07',
    '1988M08',
    '1988M09',
    '1988M10',
    '1988M11',
    '1988M12',
    '1989M01',
    '1989M02',
    '1989M03',
    '1989M04',
    '1989M05',
    '1989M06',
    '1989M07',
    '1989M08',
    '1989M09',
    '1989M10',
    '1989M11',
    '1989M12',
    '1990M01',
    '1990M02',
    '1990M03',
    '1990M04',
    '1990M05',
    '1990M06',
    '1990M07',
    '1990M08',
    '1990M09',
    '1990M10',
    '1990M11',
    '1990M12',
    '1991M01',
    '1991M02',
    '1991M03',
    '1991M04',
    '1991M05',
    '1991M06',
    '1991M07',
    '1991M08',
    '1991M09',
    '1991M10',
    '1991M11',
    '1991M12',
    '1992M01',
    '1992M02',
    '1992M03',
    '1992M04',
    '1992M05',
    '1992M06',
    '1992M07',
    '1992M08',
    '1992M09',
    '1992M10',
    '1992M11',
    '1992M12',
    '1993M01',
    '1993M02',
    '1993M03',
    '1993M04',
    '1993M05',
    '1993M06',
    '1993M07',
    '1993M08',
    '1993M09',
    '1993M10',
    '1993M11',
    '1993M12',
    '1994M01',
    '1994M02',
    '1994M03',
    '1994M04',
    '1994M05',
    '1994M06',
    '1994M07',
    '1994M08',
    '1994M09',
    '1994M10',
    '1994M11',
    '1994M12',
    '1995M01',
    '1995M02',
    '1995M03',
    '1995M04',
    '1995M05',
    '1995M06',
    '1995M07',
    '1995M08',
    '1995M09',
    '1995M10',
    '1995M11',
    '1995M12',
    '1996M01',
    '1996M02',
    '1996M03',
    '1996M04',
    '1996M05',
    '1996M06',
    '1996M07',
    '1996M08',
    '1996M09',
    '1996M10',
    '1996M11',
    '1996M12',
    '1997M01',
    '1997M02',
    '1997M03',
    '1997M04',
    '1997M05',
    '1997M06',
    '1997M07',
    '1997M08',
    '1997M09',
    '1997M10',
    '1997M11',
    '1997M12',
    '1998M01',
    '1998M02',
    '1998M03',
    '1998M04',
    '1998M05',
    '1998M06',
    '1998M07',
    '1998M08',
    '1998M09',
    '1998M10',
    '1998M11',
    '1998M12',
    '1999M01',
    '1999M02',
    '1999M03',
    '1999M04',
    '1999M05',
    '1999M06',
    '1999M07',
    '1999M08',
    '1999M09',
    '1999M10',
    '1999M11',
    '1999M12',
    '2000M01',
    '2000M02',
    '2000M03',
    '2000M04',
    '2000M05',
    '2000M06',
    '2000M07',
    '2000M08',
    '2000M09',
    '2000M10',
    '2000M11',
    '2000M12',
    '2001M01',
    '2001M02',
    '2001M03',
    '2001M04',
    '2001M05',
    '2001M06',
    '2001M07',
    '2001M08',
    '2001M09',
    '2001M10',
    '2001M11',
    '2001M12',
    '2002M01',
    '2002M02',
    '2002M03',
    '2002M04',
    '2002M05',
    '2002M06',
    '2002M07',
    '2002M08',
    '2002M09',
    '2002M10',
    '2002M11',
    '2002M12',
    '2003M01',
    '2003M02',
    '2003M03',
    '2003M04',
    '2003M05',
    '2003M06',
    '2003M07',
    '2003M08',
    '2003M09',
    '2003M10',
    '2003M11',
    '2003M12',
    '2004M01',
    '2004M02',
    '2004M03',
    '2004M04',
    '2004M05',
    '2004M06',
    '2004M07',
    '2004M08',
    '2004M09',
    '2004M10',
    '2004M11',
    '2004M12',
    '2005M01',
    '2005M02',
    '2005M03',
    '2005M04',
    '2005M05',
    '2005M06',
    '2005M07',
    '2005M08',
    '2005M09',
    '2005M10',
    '2005M11',
    '2005M12',
    '2006M01',
    '2006M02',
    '2006M03',
    '2006M04',
    '2006M05',
    '2006M06',
    '2006M07',
    '2006M08',
    '2006M09',
    '2006M10',
    '2006M11',
    '2006M12',
    '2007M01',
    '2007M02',
    '2007M03',
    '2007M04',
    '2007M05',
    '2007M06',
    '2007M07',
    '2007M08',
    '2007M09',
    '2007M10',
    '2007M11',
    '2007M12',
    '2008M01',
    '2008M02',
    '2008M03',
    '2008M04',
    '2008M05',
    '2008M06',
    '2008M07',
    '2008M08',
    '2008M09',
    '2008M10',
    '2008M11',
    '2008M12',
    '2009M01',
    '2009M02',
    '2009M03',
    '2009M04',
    '2009M05',
    '2009M06',
    '2009M07',
    '2009M08',
    '2009M09',
    '2009M10',
    '2009M11',
    '2009M12',
    '2010M01',
    '2010M02',
    '2010M03',
    '2010M04',
    '2010M05',
    '2010M06',
    '2010M07',
    '2010M08',
    '2010M09',
    '2010M10',
    '2010M11',
    '2010M12',
    '2011M01',
    '2011M02',
    '2011M03',
    '2011M04',
    '2011M05',
    '2011M06',
    '2011M07',
    '2011M08',
    '2011M09',
    '2011M10',
    '2011M11',
    '2011M12',
    '2012M01',
    '2012M02',
    '2012M03',
    '2012M04',
    '2012M05',
    '2012M06',
    '2012M07',
    '2012M08',
    '2012M09',
    '2012M10',
    '2012M11',
    '2012M12',
    '2013M01',
    '2013M02',
    '2013M03',
    '2013M04',
    '2013M05',
    '2013M06',
    '2013M07',
    '2013M08',
    '2013M09',
    '2013M10',
    '2013M11',
    '2013M12',
    '2014M01',
    '2014M02',
    '2014M03',
    '2014M04',
    '2014M05',
    '2014M06',
    '2014M07',
    '2014M08',
    '2014M09',
    '2014M10',
    '2014M11',
    '2014M12',
    '2015M01',
    '2015M02',
    '2015M03',
    '2015M04',
    '2015M05',
    '2015M06',
    '2015M07',
    '2015M08',
    '2015M09',
    '2015M10',
    '2015M11',
    '2015M12',
    '2016M01',
    '2016M02',
    '2016M03',
    '2016M04',
    '2016M05',
    '2016M06',
    '2016M07',
    '2016M08',
    '2016M09',
    '2016M10',
    '2016M11',
    '2016M12',
    '2017M01',
    '2017M02',
    '2017M03',
    '2017M04',
    '2017M05',
    '2017M06',
    '2017M07',
    '2017M08',
    '2017M09',
    '2017M10',
    '2017M11',
    '2017M12',
    '2018M01',
    '2018M02',
    '2018M03',
    '2018M04',
    '2018M05',
    '2018M06',
    '2018M07',
    '2018M08',
    '2018M09',
    '2018M10',
    '2018M11',
    '2018M12',
    '2019M01',
    '2019M02',
    '2019M03',
    '2019M04',
    '2019M05',
    '2019M06',
    '2019M07',
    '2019M08',
    '2019M09',
    '2019M10',
    '2019M11',
    '2019M12',
    '2020M01',
    '2020M02',
    '2020M03',
    '2020M04',
    '2020M05',
    '2020M06',
    '2020M07',
    '2020M08',
    '2020M09',
    '2020M10',
    '2020M11',
    '2020M12'],
   'valueTexts': ['1970M01',
    '1970M02',
    '1970M03',
    '1970M04',
    '1970M05',
    '1970M06',
    '1970M07',
    '1970M08',
    '1970M09',
    '1970M10',
    '1970M11',
    '1970M12',
    '1971M01',
    '1971M02',
    '1971M03',
    '1971M04',
    '1971M05',
    '1971M06',
    '1971M07',
    '1971M08',
    '1971M09',
    '1971M10',
    '1971M11',
    '1971M12',
    '1972M01',
    '1972M02',
    '1972M03',
    '1972M04',
    '1972M05',
    '1972M06',
    '1972M07',
    '1972M08',
    '1972M09',
    '1972M10',
    '1972M11',
    '1972M12',
    '1973M01',
    '1973M02',
    '1973M03',
    '1973M04',
    '1973M05',
    '1973M06',
    '1973M07',
    '1973M08',
    '1973M09',
    '1973M10',
    '1973M11',
    '1973M12',
    '1974M01',
    '1974M02',
    '1974M03',
    '1974M04',
    '1974M05',
    '1974M06',
    '1974M07',
    '1974M08',
    '1974M09',
    '1974M10',
    '1974M11',
    '1974M12',
    '1975M01',
    '1975M02',
    '1975M03',
    '1975M04',
    '1975M05',
    '1975M06',
    '1975M07',
    '1975M08',
    '1975M09',
    '1975M10',
    '1975M11',
    '1975M12',
    '1976M01',
    '1976M02',
    '1976M03',
    '1976M04',
    '1976M05',
    '1976M06',
    '1976M07',
    '1976M08',
    '1976M09',
    '1976M10',
    '1976M11',
    '1976M12',
    '1977M01',
    '1977M02',
    '1977M03',
    '1977M04',
    '1977M05',
    '1977M06',
    '1977M07',
    '1977M08',
    '1977M09',
    '1977M10',
    '1977M11',
    '1977M12',
    '1978M01',
    '1978M02',
    '1978M03',
    '1978M04',
    '1978M05',
    '1978M06',
    '1978M07',
    '1978M08',
    '1978M09',
    '1978M10',
    '1978M11',
    '1978M12',
    '1979M01',
    '1979M02',
    '1979M03',
    '1979M04',
    '1979M05',
    '1979M06',
    '1979M07',
    '1979M08',
    '1979M09',
    '1979M10',
    '1979M11',
    '1979M12',
    '1980M01',
    '1980M02',
    '1980M03',
    '1980M04',
    '1980M05',
    '1980M06',
    '1980M07',
    '1980M08',
    '1980M09',
    '1980M10',
    '1980M11',
    '1980M12',
    '1981M01',
    '1981M02',
    '1981M03',
    '1981M04',
    '1981M05',
    '1981M06',
    '1981M07',
    '1981M08',
    '1981M09',
    '1981M10',
    '1981M11',
    '1981M12',
    '1982M01',
    '1982M02',
    '1982M03',
    '1982M04',
    '1982M05',
    '1982M06',
    '1982M07',
    '1982M08',
    '1982M09',
    '1982M10',
    '1982M11',
    '1982M12',
    '1983M01',
    '1983M02',
    '1983M03',
    '1983M04',
    '1983M05',
    '1983M06',
    '1983M07',
    '1983M08',
    '1983M09',
    '1983M10',
    '1983M11',
    '1983M12',
    '1984M01',
    '1984M02',
    '1984M03',
    '1984M04',
    '1984M05',
    '1984M06',
    '1984M07',
    '1984M08',
    '1984M09',
    '1984M10',
    '1984M11',
    '1984M12',
    '1985M01',
    '1985M02',
    '1985M03',
    '1985M04',
    '1985M05',
    '1985M06',
    '1985M07',
    '1985M08',
    '1985M09',
    '1985M10',
    '1985M11',
    '1985M12',
    '1986M01',
    '1986M02',
    '1986M03',
    '1986M04',
    '1986M05',
    '1986M06',
    '1986M07',
    '1986M08',
    '1986M09',
    '1986M10',
    '1986M11',
    '1986M12',
    '1987M01',
    '1987M02',
    '1987M03',
    '1987M04',
    '1987M05',
    '1987M06',
    '1987M07',
    '1987M08',
    '1987M09',
    '1987M10',
    '1987M11',
    '1987M12',
    '1988M01',
    '1988M02',
    '1988M03',
    '1988M04',
    '1988M05',
    '1988M06',
    '1988M07',
    '1988M08',
    '1988M09',
    '1988M10',
    '1988M11',
    '1988M12',
    '1989M01',
    '1989M02',
    '1989M03',
    '1989M04',
    '1989M05',
    '1989M06',
    '1989M07',
    '1989M08',
    '1989M09',
    '1989M10',
    '1989M11',
    '1989M12',
    '1990M01',
    '1990M02',
    '1990M03',
    '1990M04',
    '1990M05',
    '1990M06',
    '1990M07',
    '1990M08',
    '1990M09',
    '1990M10',
    '1990M11',
    '1990M12',
    '1991M01',
    '1991M02',
    '1991M03',
    '1991M04',
    '1991M05',
    '1991M06',
    '1991M07',
    '1991M08',
    '1991M09',
    '1991M10',
    '1991M11',
    '1991M12',
    '1992M01',
    '1992M02',
    '1992M03',
    '1992M04',
    '1992M05',
    '1992M06',
    '1992M07',
    '1992M08',
    '1992M09',
    '1992M10',
    '1992M11',
    '1992M12',
    '1993M01',
    '1993M02',
    '1993M03',
    '1993M04',
    '1993M05',
    '1993M06',
    '1993M07',
    '1993M08',
    '1993M09',
    '1993M10',
    '1993M11',
    '1993M12',
    '1994M01',
    '1994M02',
    '1994M03',
    '1994M04',
    '1994M05',
    '1994M06',
    '1994M07',
    '1994M08',
    '1994M09',
    '1994M10',
    '1994M11',
    '1994M12',
    '1995M01',
    '1995M02',
    '1995M03',
    '1995M04',
    '1995M05',
    '1995M06',
    '1995M07',
    '1995M08',
    '1995M09',
    '1995M10',
    '1995M11',
    '1995M12',
    '1996M01',
    '1996M02',
    '1996M03',
    '1996M04',
    '1996M05',
    '1996M06',
    '1996M07',
    '1996M08',
    '1996M09',
    '1996M10',
    '1996M11',
    '1996M12',
    '1997M01',
    '1997M02',
    '1997M03',
    '1997M04',
    '1997M05',
    '1997M06',
    '1997M07',
    '1997M08',
    '1997M09',
    '1997M10',
    '1997M11',
    '1997M12',
    '1998M01',
    '1998M02',
    '1998M03',
    '1998M04',
    '1998M05',
    '1998M06',
    '1998M07',
    '1998M08',
    '1998M09',
    '1998M10',
    '1998M11',
    '1998M12',
    '1999M01',
    '1999M02',
    '1999M03',
    '1999M04',
    '1999M05',
    '1999M06',
    '1999M07',
    '1999M08',
    '1999M09',
    '1999M10',
    '1999M11',
    '1999M12',
    '2000M01',
    '2000M02',
    '2000M03',
    '2000M04',
    '2000M05',
    '2000M06',
    '2000M07',
    '2000M08',
    '2000M09',
    '2000M10',
    '2000M11',
    '2000M12',
    '2001M01',
    '2001M02',
    '2001M03',
    '2001M04',
    '2001M05',
    '2001M06',
    '2001M07',
    '2001M08',
    '2001M09',
    '2001M10',
    '2001M11',
    '2001M12',
    '2002M01',
    '2002M02',
    '2002M03',
    '2002M04',
    '2002M05',
    '2002M06',
    '2002M07',
    '2002M08',
    '2002M09',
    '2002M10',
    '2002M11',
    '2002M12',
    '2003M01',
    '2003M02',
    '2003M03',
    '2003M04',
    '2003M05',
    '2003M06',
    '2003M07',
    '2003M08',
    '2003M09',
    '2003M10',
    '2003M11',
    '2003M12',
    '2004M01',
    '2004M02',
    '2004M03',
    '2004M04',
    '2004M05',
    '2004M06',
    '2004M07',
    '2004M08',
    '2004M09',
    '2004M10',
    '2004M11',
    '2004M12',
    '2005M01',
    '2005M02',
    '2005M03',
    '2005M04',
    '2005M05',
    '2005M06',
    '2005M07',
    '2005M08',
    '2005M09',
    '2005M10',
    '2005M11',
    '2005M12',
    '2006M01',
    '2006M02',
    '2006M03',
    '2006M04',
    '2006M05',
    '2006M06',
    '2006M07',
    '2006M08',
    '2006M09',
    '2006M10',
    '2006M11',
    '2006M12',
    '2007M01',
    '2007M02',
    '2007M03',
    '2007M04',
    '2007M05',
    '2007M06',
    '2007M07',
    '2007M08',
    '2007M09',
    '2007M10',
    '2007M11',
    '2007M12',
    '2008M01',
    '2008M02',
    '2008M03',
    '2008M04',
    '2008M05',
    '2008M06',
    '2008M07',
    '2008M08',
    '2008M09',
    '2008M10',
    '2008M11',
    '2008M12',
    '2009M01',
    '2009M02',
    '2009M03',
    '2009M04',
    '2009M05',
    '2009M06',
    '2009M07',
    '2009M08',
    '2009M09',
    '2009M10',
    '2009M11',
    '2009M12',
    '2010M01',
    '2010M02',
    '2010M03',
    '2010M04',
    '2010M05',
    '2010M06',
    '2010M07',
    '2010M08',
    '2010M09',
    '2010M10',
    '2010M11',
    '2010M12',
    '2011M01',
    '2011M02',
    '2011M03',
    '2011M04',
    '2011M05',
    '2011M06',
    '2011M07',
    '2011M08',
    '2011M09',
    '2011M10',
    '2011M11',
    '2011M12',
    '2012M01',
    '2012M02',
    '2012M03',
    '2012M04',
    '2012M05',
    '2012M06',
    '2012M07',
    '2012M08',
    '2012M09',
    '2012M10',
    '2012M11',
    '2012M12',
    '2013M01',
    '2013M02',
    '2013M03',
    '2013M04',
    '2013M05',
    '2013M06',
    '2013M07',
    '2013M08',
    '2013M09',
    '2013M10',
    '2013M11',
    '2013M12',
    '2014M01',
    '2014M02',
    '2014M03',
    '2014M04',
    '2014M05',
    '2014M06',
    '2014M07',
    '2014M08',
    '2014M09',
    '2014M10',
    '2014M11',
    '2014M12',
    '2015M01',
    '2015M02',
    '2015M03',
    '2015M04',
    '2015M05',
    '2015M06',
    '2015M07',
    '2015M08',
    '2015M09',
    '2015M10',
    '2015M11',
    '2015M12',
    '2016M01',
    '2016M02',
    '2016M03',
    '2016M04',
    '2016M05',
    '2016M06',
    '2016M07',
    '2016M08',
    '2016M09',
    '2016M10',
    '2016M11',
    '2016M12',
    '2017M01',
    '2017M02',
    '2017M03',
    '2017M04',
    '2017M05',
    '2017M06',
    '2017M07',
    '2017M08',
    '2017M09',
    '2017M10',
    '2017M11',
    '2017M12',
    '2018M01',
    '2018M02',
    '2018M03',
    '2018M04',
    '2018M05',
    '2018M06',
    '2018M07',
    '2018M08',
    '2018M09',
    '2018M10',
    '2018M11',
    '2018M12',
    '2019M01',
    '2019M02',
    '2019M03',
    '2019M04',
    '2019M05',
    '2019M06',
    '2019M07',
    '2019M08',
    '2019M09',
    '2019M10',
    '2019M11',
    '2019M12',
    '2020M01',
    '2020M02',
    '2020M03',
    '2020M04',
    '2020M05',
    '2020M06',
    '2020M07',
    '2020M08',
    '2020M09',
    '2020M10',
    '2020M11',
    '2020M12'],
   'time': True}]}

In [7]:
# Get information about available variables at the current level
scb.get_variables()

{'kön': ['män', 'kvinnor', 'totalt'],
 'ålder': ['15-19 år',
  '15-24 år',
  '20-24 år',
  '25-34 år',
  '35-44 år',
  '45-54 år',
  '55-64 år',
  '65-74 år',
  'totalt 15-74 år',
  'totalt 16-64 år',
  'totalt 16-65 år',
  'totalt 16-66 år',
  'totalt 20-64 år',
  'totalt 20-65 år',
  'totalt 20-66 år'],
 'arbetskraftstillhörighet': ['sysselsatta',
  'sysselsatta i arbete',
  'sysselsatta frånvarande hela veckan'],
 'tabellinnehåll': ['1000-tal', 'Felmarginal ±, 1000-tal'],
 'månad': ['1970M01',
  '1970M02',
  '1970M03',
  '1970M04',
  '1970M05',
  '1970M06',
  '1970M07',
  '1970M08',
  '1970M09',
  '1970M10',
  '1970M11',
  '1970M12',
  '1971M01',
  '1971M02',
  '1971M03',
  '1971M04',
  '1971M05',
  '1971M06',
  '1971M07',
  '1971M08',
  '1971M09',
  '1971M10',
  '1971M11',
  '1971M12',
  '1972M01',
  '1972M02',
  '1972M03',
  '1972M04',
  '1972M05',
  '1972M06',
  '1972M07',
  '1972M08',
  '1972M09',
  '1972M10',
  '1972M11',
  '1972M12',
  '1973M01',
  '1973M02',
  '1973M03',
  '1973M04',
  '1973M05',
  '1973M06',
  '1973M07',
  '1973M08',
  '1973M09',
  '1973M10',
  '1973M11',
  '1973M12',
  '1974M01',
  '1974M02',
  '1974M03',
  '1974M04',
  '1974M05',
  '1974M06',
  '1974M07',
  '1974M08',
  '1974M09',
  '1974M10',
  '1974M11',
  '1974M12',
  '1975M01',
  '1975M02',
  '1975M03',
  '1975M04',
  '1975M05',
  '1975M06',
  '1975M07',
  '1975M08',
  '1975M09',
  '1975M10',
  '1975M11',
  '1975M12',
  '1976M01',
  '1976M02',
  '1976M03',
  '1976M04',
  '1976M05',
  '1976M06',
  '1976M07',
  '1976M08',
  '1976M09',
  '1976M10',
  '1976M11',
  '1976M12',
  '1977M01',
  '1977M02',
  '1977M03',
  '1977M04',
  '1977M05',
  '1977M06',
  '1977M07',
  '1977M08',
  '1977M09',
  '1977M10',
  '1977M11',
  '1977M12',
  '1978M01',
  '1978M02',
  '1978M03',
  '1978M04',
  '1978M05',
  '1978M06',
  '1978M07',
  '1978M08',
  '1978M09',
  '1978M10',
  '1978M11',
  '1978M12',
  '1979M01',
  '1979M02',
  '1979M03',
  '1979M04',
  '1979M05',
  '1979M06',
  '1979M07',
  '1979M08',
  '1979M09',
  '1979M10',
  '1979M11',
  '1979M12',
  '1980M01',
  '1980M02',
  '1980M03',
  '1980M04',
  '1980M05',
  '1980M06',
  '1980M07',
  '1980M08',
  '1980M09',
  '1980M10',
  '1980M11',
  '1980M12',
  '1981M01',
  '1981M02',
  '1981M03',
  '1981M04',
  '1981M05',
  '1981M06',
  '1981M07',
  '1981M08',
  '1981M09',
  '1981M10',
  '1981M11',
  '1981M12',
  '1982M01',
  '1982M02',
  '1982M03',
  '1982M04',
  '1982M05',
  '1982M06',
  '1982M07',
  '1982M08',
  '1982M09',
  '1982M10',
  '1982M11',
  '1982M12',
  '1983M01',
  '1983M02',
  '1983M03',
  '1983M04',
  '1983M05',
  '1983M06',
  '1983M07',
  '1983M08',
  '1983M09',
  '1983M10',
  '1983M11',
  '1983M12',
  '1984M01',
  '1984M02',
  '1984M03',
  '1984M04',
  '1984M05',
  '1984M06',
  '1984M07',
  '1984M08',
  '1984M09',
  '1984M10',
  '1984M11',
  '1984M12',
  '1985M01',
  '1985M02',
  '1985M03',
  '1985M04',
  '1985M05',
  '1985M06',
  '1985M07',
  '1985M08',
  '1985M09',
  '1985M10',
  '1985M11',
  '1985M12',
  '1986M01',
  '1986M02',
  '1986M03',
  '1986M04',
  '1986M05',
  '1986M06',
  '1986M07',
  '1986M08',
  '1986M09',
  '1986M10',
  '1986M11',
  '1986M12',
  '1987M01',
  '1987M02',
  '1987M03',
  '1987M04',
  '1987M05',
  '1987M06',
  '1987M07',
  '1987M08',
  '1987M09',
  '1987M10',
  '1987M11',
  '1987M12',
  '1988M01',
  '1988M02',
  '1988M03',
  '1988M04',
  '1988M05',
  '1988M06',
  '1988M07',
  '1988M08',
  '1988M09',
  '1988M10',
  '1988M11',
  '1988M12',
  '1989M01',
  '1989M02',
  '1989M03',
  '1989M04',
  '1989M05',
  '1989M06',
  '1989M07',
  '1989M08',
  '1989M09',
  '1989M10',
  '1989M11',
  '1989M12',
  '1990M01',
  '1990M02',
  '1990M03',
  '1990M04',
  '1990M05',
  '1990M06',
  '1990M07',
  '1990M08',
  '1990M09',
  '1990M10',
  '1990M11',
  '1990M12',
  '1991M01',
  '1991M02',
  '1991M03',
  '1991M04',
  '1991M05',
  '1991M06',
  '1991M07',
  '1991M08',
  '1991M09',
  '1991M10',
  '1991M11',
  '1991M12',
  '1992M01',
  '1992M02',
  '1992M03',
  '1992M04',
  '1992M05',
  '1992M06',
  '1992M07',
  '1992M08',
  '1992M09',
  '1992M10',
  '1992M11',
  '1992M12',
  '1993M01',
  '1993M02',
  '1993M03',
  '1993M04',
  '1993M05',
  '1993M06',
  '1993M07',
  '1993M08',
  '1993M09',
  '1993M10',
  '1993M11',
  '1993M12',
  '1994M01',
  '1994M02',
  '1994M03',
  '1994M04',
  '1994M05',
  '1994M06',
  '1994M07',
  '1994M08',
  '1994M09',
  '1994M10',
  '1994M11',
  '1994M12',
  '1995M01',
  '1995M02',
  '1995M03',
  '1995M04',
  '1995M05',
  '1995M06',
  '1995M07',
  '1995M08',
  '1995M09',
  '1995M10',
  '1995M11',
  '1995M12',
  '1996M01',
  '1996M02',
  '1996M03',
  '1996M04',
  '1996M05',
  '1996M06',
  '1996M07',
  '1996M08',
  '1996M09',
  '1996M10',
  '1996M11',
  '1996M12',
  '1997M01',
  '1997M02',
  '1997M03',
  '1997M04',
  '1997M05',
  '1997M06',
  '1997M07',
  '1997M08',
  '1997M09',
  '1997M10',
  '1997M11',
  '1997M12',
  '1998M01',
  '1998M02',
  '1998M03',
  '1998M04',
  '1998M05',
  '1998M06',
  '1998M07',
  '1998M08',
  '1998M09',
  '1998M10',
  '1998M11',
  '1998M12',
  '1999M01',
  '1999M02',
  '1999M03',
  '1999M04',
  '1999M05',
  '1999M06',
  '1999M07',
  '1999M08',
  '1999M09',
  '1999M10',
  '1999M11',
  '1999M12',
  '2000M01',
  '2000M02',
  '2000M03',
  '2000M04',
  '2000M05',
  '2000M06',
  '2000M07',
  '2000M08',
  '2000M09',
  '2000M10',
  '2000M11',
  '2000M12',
  '2001M01',
  '2001M02',
  '2001M03',
  '2001M04',
  '2001M05',
  '2001M06',
  '2001M07',
  '2001M08',
  '2001M09',
  '2001M10',
  '2001M11',
  '2001M12',
  '2002M01',
  '2002M02',
  '2002M03',
  '2002M04',
  '2002M05',
  '2002M06',
  '2002M07',
  '2002M08',
  '2002M09',
  '2002M10',
  '2002M11',
  '2002M12',
  '2003M01',
  '2003M02',
  '2003M03',
  '2003M04',
  '2003M05',
  '2003M06',
  '2003M07',
  '2003M08',
  '2003M09',
  '2003M10',
  '2003M11',
  '2003M12',
  '2004M01',
  '2004M02',
  '2004M03',
  '2004M04',
  '2004M05',
  '2004M06',
  '2004M07',
  '2004M08',
  '2004M09',
  '2004M10',
  '2004M11',
  '2004M12',
  '2005M01',
  '2005M02',
  '2005M03',
  '2005M04',
  '2005M05',
  '2005M06',
  '2005M07',
  '2005M08',
  '2005M09',
  '2005M10',
  '2005M11',
  '2005M12',
  '2006M01',
  '2006M02',
  '2006M03',
  '2006M04',
  '2006M05',
  '2006M06',
  '2006M07',
  '2006M08',
  '2006M09',
  '2006M10',
  '2006M11',
  '2006M12',
  '2007M01',
  '2007M02',
  '2007M03',
  '2007M04',
  '2007M05',
  '2007M06',
  '2007M07',
  '2007M08',
  '2007M09',
  '2007M10',
  '2007M11',
  '2007M12',
  '2008M01',
  '2008M02',
  '2008M03',
  '2008M04',
  '2008M05',
  '2008M06',
  '2008M07',
  '2008M08',
  '2008M09',
  '2008M10',
  '2008M11',
  '2008M12',
  '2009M01',
  '2009M02',
  '2009M03',
  '2009M04',
  '2009M05',
  '2009M06',
  '2009M07',
  '2009M08',
  '2009M09',
  '2009M10',
  '2009M11',
  '2009M12',
  '2010M01',
  '2010M02',
  '2010M03',
  '2010M04',
  '2010M05',
  '2010M06',
  '2010M07',
  '2010M08',
  '2010M09',
  '2010M10',
  '2010M11',
  '2010M12',
  '2011M01',
  '2011M02',
  '2011M03',
  '2011M04',
  '2011M05',
  '2011M06',
  '2011M07',
  '2011M08',
  '2011M09',
  '2011M10',
  '2011M11',
  '2011M12',
  '2012M01',
  '2012M02',
  '2012M03',
  '2012M04',
  '2012M05',
  '2012M06',
  '2012M07',
  '2012M08',
  '2012M09',
  '2012M10',
  '2012M11',
  '2012M12',
  '2013M01',
  '2013M02',
  '2013M03',
  '2013M04',
  '2013M05',
  '2013M06',
  '2013M07',
  '2013M08',
  '2013M09',
  '2013M10',
  '2013M11',
  '2013M12',
  '2014M01',
  '2014M02',
  '2014M03',
  '2014M04',
  '2014M05',
  '2014M06',
  '2014M07',
  '2014M08',
  '2014M09',
  '2014M10',
  '2014M11',
  '2014M12',
  '2015M01',
  '2015M02',
  '2015M03',
  '2015M04',
  '2015M05',
  '2015M06',
  '2015M07',
  '2015M08',
  '2015M09',
  '2015M10',
  '2015M11',
  '2015M12',
  '2016M01',
  '2016M02',
  '2016M03',
  '2016M04',
  '2016M05',
  '2016M06',
  '2016M07',
  '2016M08',
  '2016M09',
  '2016M10',
  '2016M11',
  '2016M12',
  '2017M01',
  '2017M02',
  '2017M03',
  '2017M04',
  '2017M05',
  '2017M06',
  '2017M07',
  '2017M08',
  '2017M09',
  '2017M10',
  '2017M11',
  '2017M12',
  '2018M01',
  '2018M02',
  '2018M03',
  '2018M04',
  '2018M05',
  '2018M06',
  '2018M07',
  '2018M08',
  '2018M09',
  '2018M10',
  '2018M11',
  '2018M12',
  '2019M01',
  '2019M02',
  '2019M03',
  '2019M04',
  '2019M05',
  '2019M06',
  '2019M07',
  '2019M08',
  '2019M09',
  '2019M10',
  '2019M11',
  '2019M12',
  '2020M01',
  '2020M02',
  '2020M03',
  '2020M04',
  '2020M05',
  '2020M06',
  '2020M07',
  '2020M08',
  '2020M09',
  '2020M10',
  '2020M11',
  '2020M12']}

In [8]:
# Defining the start and end years
start_year = 2000
end_year = 2020

# Defining the months
months = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]

# Initialize an empty list to store the formatted dates
formatted_dates = []

# Loop through the years and months
for year in range(start_year, end_year + 1):
    for month in months:
        formatted_date = f"{year}M{month}"
        formatted_dates.append(formatted_date)

# The 'formatted_dates' list now contains the desired date strings
print(formatted_dates)

['2000M01', '2000M02', '2000M03', '2000M04', '2000M05', '2000M06', '2000M07', '2000M08', '2000M09', '2000M10', '2000M11', '2000M12', '2001M01', '2001M02', '2001M03', '2001M04', '2001M05', '2001M06', '2001M07', '2001M08', '2001M09', '2001M10', '2001M11', '2001M12', '2002M01', '2002M02', '2002M03', '2002M04', '2002M05', '2002M06', '2002M07', '2002M08', '2002M09', '2002M10', '2002M11', '2002M12', '2003M01', '2003M02', '2003M03', '2003M04', '2003M05', '2003M06', '2003M07', '2003M08', '2003M09', '2003M10', '2003M11', '2003M12', '2004M01', '2004M02', '2004M03', '2004M04', '2004M05', '2004M06', '2004M07', '2004M08', '2004M09', '2004M10', '2004M11', '2004M12', '2005M01', '2005M02', '2005M03', '2005M04', '2005M05', '2005M06', '2005M07', '2005M08', '2005M09', '2005M10', '2005M11', '2005M12', '2006M01', '2006M02', '2006M03', '2006M04', '2006M05', '2006M06', '2006M07', '2006M08', '2006M09', '2006M10', '2006M11', '2006M12', '2007M01', '2007M02', '2007M03', '2007M04', '2007M05', '2007M06', '2007M07', '2007M08', '2007M09', '2007M10', '2007M11', '2007M12', '2008M01', '2008M02', '2008M03', '2008M04', '2008M05', '2008M06', '2008M07', '2008M08', '2008M09', '2008M10', '2008M11', '2008M12', '2009M01', '2009M02', '2009M03', '2009M04', '2009M05', '2009M06', '2009M07', '2009M08', '2009M09', '2009M10', '2009M11', '2009M12', '2010M01', '2010M02', '2010M03', '2010M04', '2010M05', '2010M06', '2010M07', '2010M08', '2010M09', '2010M10', '2010M11', '2010M12', '2011M01', '2011M02', '2011M03', '2011M04', '2011M05', '2011M06', '2011M07', '2011M08', '2011M09', '2011M10', '2011M11', '2011M12', '2012M01', '2012M02', '2012M03', '2012M04', '2012M05', '2012M06', '2012M07', '2012M08', '2012M09', '2012M10', '2012M11', '2012M12', '2013M01', '2013M02', '2013M03', '2013M04', '2013M05', '2013M06', '2013M07', '2013M08', '2013M09', '2013M10', '2013M11', '2013M12', '2014M01', '2014M02', '2014M03', '2014M04', '2014M05', '2014M06', '2014M07', '2014M08', '2014M09', '2014M10', '2014M11', '2014M12', '2015M01', '2015M02', '2015M03', '2015M04', '2015M05', '2015M06', '2015M07', '2015M08', '2015M09', '2015M10', '2015M11', '2015M12', '2016M01', '2016M02', '2016M03', '2016M04', '2016M05', '2016M06', '2016M07', '2016M08', '2016M09', '2016M10', '2016M11', '2016M12', '2017M01', '2017M02', '2017M03', '2017M04', '2017M05', '2017M06', '2017M07', '2017M08', '2017M09', '2017M10', '2017M11', '2017M12', '2018M01', '2018M02', '2018M03', '2018M04', '2018M05', '2018M06', '2018M07', '2018M08', '2018M09', '2018M10', '2018M11', '2018M12', '2019M01', '2019M02', '2019M03', '2019M04', '2019M05', '2019M06', '2019M07', '2019M08', '2019M09', '2019M10', '2019M11', '2019M12', '2020M01', '2020M02', '2020M03', '2020M04', '2020M05', '2020M06', '2020M07', '2020M08', '2020M09', '2020M10', '2020M11', '2020M12']

In [9]:
# Set the query parameters for the SCB API using the formatted dates

scb.set_query(ålder='totalt 15-74 år',
              arbetskraftstillhörighet=['sysselsatta', 'sysselsatta i arbete'],
              tabellinnehåll = ['1000-tal', 'Felmarginal ±, 1000-tal'],
              månad=formatted_dates)

In [10]:
# Retrieve data from the SCB API
scb_data = scb.get_data()

In [11]:
# Extract the 'data' key from the response
scb_uttag = scb_data['data']

In [12]:
type(scb_data)

dict

In [13]:
type(scb_uttag)

list

In [14]:
scb_uttag

[{'key': ['tot15-74', 'SYS', '2000M01'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2000M02'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2000M03'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2000M04'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2000M05'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2000M06'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2000M07'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2000M08'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2000M09'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2000M10'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2000M11'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2000M12'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'SYS', '2001M01'], 'values': ['4236.0', '..']},
 {'key': ['tot15-74', 'SYS', '2001M02'], 'values': ['4288.5', '..']},
 {'key': ['tot15-74', 'SYS', '2001M03'], 'values': ['4285.3', '..']},
 {'key': ['tot15-74', 'SYS', '2001M04'], 'values': ['4309.3', '..']},
 {'key': ['tot15-74', 'SYS', '2001M05'], 'values': ['4328.1', '..']},
 {'key': ['tot15-74', 'SYS', '2001M06'], 'values': ['4455.8', '..']},
 {'key': ['tot15-74', 'SYS', '2001M07'], 'values': ['4511.8', '..']},
 {'key': ['tot15-74', 'SYS', '2001M08'], 'values': ['4413.1', '..']},
 {'key': ['tot15-74', 'SYS', '2001M09'], 'values': ['4344.2', '..']},
 {'key': ['tot15-74', 'SYS', '2001M10'], 'values': ['4325.5', '..']},
 {'key': ['tot15-74', 'SYS', '2001M11'], 'values': ['4325.2', '..']},
 {'key': ['tot15-74', 'SYS', '2001M12'], 'values': ['4338.1', '..']},
 {'key': ['tot15-74', 'SYS', '2002M01'], 'values': ['4266.0', '..']},
 {'key': ['tot15-74', 'SYS', '2002M02'], 'values': ['4295.9', '..']},
 {'key': ['tot15-74', 'SYS', '2002M03'], 'values': ['4328.7', '..']},
 {'key': ['tot15-74', 'SYS', '2002M04'], 'values': ['4292.4', '..']},
 {'key': ['tot15-74', 'SYS', '2002M05'], 'values': ['4331.6', '..']},
 {'key': ['tot15-74', 'SYS', '2002M06'], 'values': ['4502.9', '..']},
 {'key': ['tot15-74', 'SYS', '2002M07'], 'values': ['4499.0', '..']},
 {'key': ['tot15-74', 'SYS', '2002M08'], 'values': ['4424.1', '..']},
 {'key': ['tot15-74', 'SYS', '2002M09'], 'values': ['4359.6', '..']},
 {'key': ['tot15-74', 'SYS', '2002M10'], 'values': ['4337.5', '..']},
 {'key': ['tot15-74', 'SYS', '2002M11'], 'values': ['4341.0', '..']},
 {'key': ['tot15-74', 'SYS', '2002M12'], 'values': ['4338.2', '..']},
 {'key': ['tot15-74', 'SYS', '2003M01'], 'values': ['4253.9', '..']},
 {'key': ['tot15-74', 'SYS', '2003M02'], 'values': ['4288.8', '..']},
 {'key': ['tot15-74', 'SYS', '2003M03'], 'values': ['4323.7', '..']},
 {'key': ['tot15-74', 'SYS', '2003M04'], 'values': ['4311.9', '..']},
 {'key': ['tot15-74', 'SYS', '2003M05'], 'values': ['4345.5', '..']},
 {'key': ['tot15-74', 'SYS', '2003M06'], 'values': ['4471.5', '..']},
 {'key': ['tot15-74', 'SYS', '2003M07'], 'values': ['4513.0', '..']},
 {'key': ['tot15-74', 'SYS', '2003M08'], 'values': ['4386.8', '..']},
 {'key': ['tot15-74', 'SYS', '2003M09'], 'values': ['4357.0', '..']},
 {'key': ['tot15-74', 'SYS', '2003M10'], 'values': ['4329.4', '..']},
 {'key': ['tot15-74', 'SYS', '2003M11'], 'values': ['4296.1', '..']},
 {'key': ['tot15-74', 'SYS', '2003M12'], 'values': ['4312.4', '..']},
 {'key': ['tot15-74', 'SYS', '2004M01'], 'values': ['4251.8', '..']},
 {'key': ['tot15-74', 'SYS', '2004M02'], 'values': ['4243.0', '..']},
 {'key': ['tot15-74', 'SYS', '2004M03'], 'values': ['4291.2', '..']},
 {'key': ['tot15-74', 'SYS', '2004M04'], 'values': ['4315.6', '..']},
 {'key': ['tot15-74', 'SYS', '2004M05'], 'values': ['4317.9', '..']},
 {'key': ['tot15-74', 'SYS', '2004M06'], 'values': ['4405.9', '..']},
 {'key': ['tot15-74', 'SYS', '2004M07'], 'values': ['4532.0', '..']},
 {'key': ['tot15-74', 'SYS', '2004M08'], 'values': ['4391.8', '..']},
 {'key': ['tot15-74', 'SYS', '2004M09'], 'values': ['4322.7', '..']},
 {'key': ['tot15-74', 'SYS', '2004M10'], 'values': ['4326.4', '..']},
 {'key': ['tot15-74', 'SYS', '2004M11'], 'values': ['4296.4', '..']},
 {'key': ['tot15-74', 'SYS', '2004M12'], 'values': ['4301.0', '..']},
 {'key': ['tot15-74', 'SYS', '2005M01'], 'values': ['4277.2', '..']},
 {'key': ['tot15-74', 'SYS', '2005M02'], 'values': ['4242.3', '..']},
 {'key': ['tot15-74', 'SYS', '2005M03'], 'values': ['4276.4', '..']},
 {'key': ['tot15-74', 'SYS', '2005M04'], 'values': ['4286.3', '40.8']},
 {'key': ['tot15-74', 'SYS', '2005M05'], 'values': ['4320.1', '40.4']},
 {'key': ['tot15-74', 'SYS', '2005M06'], 'values': ['4452.3', '41.7']},
 {'key': ['tot15-74', 'SYS', '2005M07'], 'values': ['4505.2', '37.8']},
 {'key': ['tot15-74', 'SYS', '2005M08'], 'values': ['4433.3', '40.1']},
 {'key': ['tot15-74', 'SYS', '2005M09'], 'values': ['4337.3', '36.2']},
 {'key': ['tot15-74', 'SYS', '2005M10'], 'values': ['4323.7', '36.6']},
 {'key': ['tot15-74', 'SYS', '2005M11'], 'values': ['4380.8', '39.0']},
 {'key': ['tot15-74', 'SYS', '2005M12'], 'values': ['4350.4', '38.3']},
 {'key': ['tot15-74', 'SYS', '2006M01'], 'values': ['4281.8', '35.9']},
 {'key': ['tot15-74', 'SYS', '2006M02'], 'values': ['4316.8', '34.6']},
 {'key': ['tot15-74', 'SYS', '2006M03'], 'values': ['4326.1', '33.4']},
 {'key': ['tot15-74', 'SYS', '2006M04'], 'values': ['4340.3', '34.6']},
 {'key': ['tot15-74', 'SYS', '2006M05'], 'values': ['4364.0', '34.3']},
 {'key': ['tot15-74', 'SYS', '2006M06'], 'values': ['4543.8', '35.3']},
 {'key': ['tot15-74', 'SYS', '2006M07'], 'values': ['4648.0', '36.6']},
 {'key': ['tot15-74', 'SYS', '2006M08'], 'values': ['4525.7', '35.5']},
 {'key': ['tot15-74', 'SYS', '2006M09'], 'values': ['4439.8', '36.2']},
 {'key': ['tot15-74', 'SYS', '2006M10'], 'values': ['4477.2', '36.3']},
 {'key': ['tot15-74', 'SYS', '2006M11'], 'values': ['4457.0', '35.6']},
 {'key': ['tot15-74', 'SYS', '2006M12'], 'values': ['4427.9', '36.1']},
 {'key': ['tot15-74', 'SYS', '2007M01'], 'values': ['4441.5', '36.8']},
 {'key': ['tot15-74', 'SYS', '2007M02'], 'values': ['4440.7', '35.5']},
 {'key': ['tot15-74', 'SYS', '2007M03'], 'values': ['4418.5', '36.8']},
 {'key': ['tot15-74', 'SYS', '2007M04'], 'values': ['4484.1', '33.8']},
 {'key': ['tot15-74', 'SYS', '2007M05'], 'values': ['4535.4', '35.7']},
 {'key': ['tot15-74', 'SYS', '2007M06'], 'values': ['4596.4', '36.0']},
 {'key': ['tot15-74', 'SYS', '2007M07'], 'values': ['4760.6', '35.8']},
 {'key': ['tot15-74', 'SYS', '2007M08'], 'values': ['4662.4', '36.2']},
 {'key': ['tot15-74', 'SYS', '2007M09'], 'values': ['4521.8', '35.7']},
 {'key': ['tot15-74', 'SYS', '2007M10'], 'values': ['4557.9', '35.1']},
 {'key': ['tot15-74', 'SYS', '2007M11'], 'values': ['4575.3', '35.6']},
 {'key': ['tot15-74', 'SYS', '2007M12'], 'values': ['4519.8', '34.9']},
 {'key': ['tot15-74', 'SYS', '2008M01'], 'values': ['4494.4', '35.7']},
 {'key': ['tot15-74', 'SYS', '2008M02'], 'values': ['4535.3', '34.6']},
 {'key': ['tot15-74', 'SYS', '2008M03'], 'values': ['4528.6', '35.4']},
 {'key': ['tot15-74', 'SYS', '2008M04'], 'values': ['4576.1', '35.2']},
 {'key': ['tot15-74', 'SYS', '2008M05'], 'values': ['4594.1', '34.3']},
 {'key': ['tot15-74', 'SYS', '2008M06'], 'values': ['4685.9', '36.6']},
 {'key': ['tot15-74', 'SYS', '2008M07'], 'values': ['4797.9', '35.5']},
 {'key': ['tot15-74', 'SYS', '2008M08'], 'values': ['4684.6', '36.6']},
 {'key': ['tot15-74', 'SYS', '2008M09'], 'values': ['4566.2', '35.2']},
 {'key': ['tot15-74', 'SYS', '2008M10'], 'values': ['4592.8', '37.6']},
 {'key': ['tot15-74', 'SYS', '2008M11'], 'values': ['4559.2', '36.2']},
 {'key': ['tot15-74', 'SYS', '2008M12'], 'values': ['4518.6', '34.4']},
 {'key': ['tot15-74', 'SYS', '2009M01'], 'values': ['4478.4', '35.1']},
 {'key': ['tot15-74', 'SYS', '2009M02'], 'values': ['4459.5', '33.8']},
 {'key': ['tot15-74', 'SYS', '2009M03'], 'values': ['4458.8', '35.3']},
 {'key': ['tot15-74', 'SYS', '2009M04'], 'values': ['4460.2', '35.4']},
 {'key': ['tot15-74', 'SYS', '2009M05'], 'values': ['4486.7', '34.9']},
 {'key': ['tot15-74', 'SYS', '2009M06'], 'values': ['4606.7', '36.6']},
 {'key': ['tot15-74', 'SYS', '2009M07'], 'values': ['4646.1', '38.1']},
 {'key': ['tot15-74', 'SYS', '2009M08'], 'values': ['4537.4', '36.6']},
 {'key': ['tot15-74', 'SYS', '2009M09'], 'values': ['4477.6', '36.9']},
 {'key': ['tot15-74', 'SYS', '2009M10'], 'values': ['4457.6', '37.9']},
 {'key': ['tot15-74', 'SYS', '2009M11'], 'values': ['4469.1', '36.9']},
 {'key': ['tot15-74', 'SYS', '2009M12'], 'values': ['4451.6', '37.3']},
 {'key': ['tot15-74', 'SYS', '2010M01'], 'values': ['4382.2', '33.0']},
 {'key': ['tot15-74', 'SYS', '2010M02'], 'values': ['4415.8', '33.0']},
 {'key': ['tot15-74', 'SYS', '2010M03'], 'values': ['4434.5', '33.5']},
 {'key': ['tot15-74', 'SYS', '2010M04'], 'values': ['4457.8', '32.2']},
 {'key': ['tot15-74', 'SYS', '2010M05'], 'values': ['4475.7', '32.8']},
 {'key': ['tot15-74', 'SYS', '2010M06'], 'values': ['4640.1', '35.0']},
 {'key': ['tot15-74', 'SYS', '2010M07'], 'values': ['4723.3', '34.6']},
 {'key': ['tot15-74', 'SYS', '2010M08'], 'values': ['4586.3', '34.3']},
 {'key': ['tot15-74', 'SYS', '2010M09'], 'values': ['4543.7', '35.2']},
 {'key': ['tot15-74', 'SYS', '2010M10'], 'values': ['4540.7', '33.5']},
 {'key': ['tot15-74', 'SYS', '2010M11'], 'values': ['4538.3', '34.5']},
 {'key': ['tot15-74', 'SYS', '2010M12'], 'values': ['4532.3', '33.6']},
 {'key': ['tot15-74', 'SYS', '2011M01'], 'values': ['4522.6', '32.0']},
 {'key': ['tot15-74', 'SYS', '2011M02'], 'values': ['4540.0', '33.2']},
 {'key': ['tot15-74', 'SYS', '2011M03'], 'values': ['4536.6', '32.8']},
 {'key': ['tot15-74', 'SYS', '2011M04'], 'values': ['4588.0', '33.0']},
 {'key': ['tot15-74', 'SYS', '2011M05'], 'values': ['4596.0', '33.3']},
 {'key': ['tot15-74', 'SYS', '2011M06'], 'values': ['4730.9', '34.8']},
 {'key': ['tot15-74', 'SYS', '2011M07'], 'values': ['4805.1', '33.7']},
 {'key': ['tot15-74', 'SYS', '2011M08'], 'values': ['4712.6', '33.8']},
 {'key': ['tot15-74', 'SYS', '2011M09'], 'values': ['4625.8', '34.0']},
 {'key': ['tot15-74', 'SYS', '2011M10'], 'values': ['4627.6', '34.0']},
 {'key': ['tot15-74', 'SYS', '2011M11'], 'values': ['4619.4', '33.7']},
 {'key': ['tot15-74', 'SYS', '2011M12'], 'values': ['4606.9', '31.9']},
 {'key': ['tot15-74', 'SYS', '2012M01'], 'values': ['4519.4', '33.1']},
 {'key': ['tot15-74', 'SYS', '2012M02'], 'values': ['4558.5', '32.6']},
 {'key': ['tot15-74', 'SYS', '2012M03'], 'values': ['4620.9', '32.6']},
 {'key': ['tot15-74', 'SYS', '2012M04'], 'values': ['4603.2', '34.2']},
 {'key': ['tot15-74', 'SYS', '2012M05'], 'values': ['4615.8', '33.0']},
 {'key': ['tot15-74', 'SYS', '2012M06'], 'values': ['4787.7', '34.1']},
 {'key': ['tot15-74', 'SYS', '2012M07'], 'values': ['4839.2', '34.9']},
 {'key': ['tot15-74', 'SYS', '2012M08'], 'values': ['4717.8', '33.8']},
 {'key': ['tot15-74', 'SYS', '2012M09'], 'values': ['4666.4', '34.0']},
 {'key': ['tot15-74', 'SYS', '2012M10'], 'values': ['4656.3', '34.5']},
 {'key': ['tot15-74', 'SYS', '2012M11'], 'values': ['4629.7', '34.1']},
 {'key': ['tot15-74', 'SYS', '2012M12'], 'values': ['4647.1', '32.4']},
 {'key': ['tot15-74', 'SYS', '2013M01'], 'values': ['4577.7', '32.3']},
 {'key': ['tot15-74', 'SYS', '2013M02'], 'values': ['4596.6', '33.0']},
 {'key': ['tot15-74', 'SYS', '2013M03'], 'values': ['4642.8', '33.0']},
 {'key': ['tot15-74', 'SYS', '2013M04'], 'values': ['4641.7', '33.6']},
 {'key': ['tot15-74', 'SYS', '2013M05'], 'values': ['4667.1', '33.5']},
 {'key': ['tot15-74', 'SYS', '2013M06'], 'values': ['4815.3', '34.7']},
 {'key': ['tot15-74', 'SYS', '2013M07'], 'values': ['4904.7', '34.4']},
 {'key': ['tot15-74', 'SYS', '2013M08'], 'values': ['4766.2', '34.1']},
 {'key': ['tot15-74', 'SYS', '2013M09'], 'values': ['4707.6', '34.6']},
 {'key': ['tot15-74', 'SYS', '2013M10'], 'values': ['4745.9', '34.8']},
 {'key': ['tot15-74', 'SYS', '2013M11'], 'values': ['4704.3', '34.6']},
 {'key': ['tot15-74', 'SYS', '2013M12'], 'values': ['4679.9', '33.6']},
 {'key': ['tot15-74', 'SYS', '2014M01'], 'values': ['4619.0', '33.5']},
 {'key': ['tot15-74', 'SYS', '2014M02'], 'values': ['4647.8', '34.1']},
 {'key': ['tot15-74', 'SYS', '2014M03'], 'values': ['4701.0', '34.1']},
 {'key': ['tot15-74', 'SYS', '2014M04'], 'values': ['4697.9', '34.7']},
 {'key': ['tot15-74', 'SYS', '2014M05'], 'values': ['4745.5', '35.2']},
 {'key': ['tot15-74', 'SYS', '2014M06'], 'values': ['4869.5', '35.6']},
 {'key': ['tot15-74', 'SYS', '2014M07'], 'values': ['4982.0', '36.3']},
 {'key': ['tot15-74', 'SYS', '2014M08'], 'values': ['4862.7', '36.1']},
 {'key': ['tot15-74', 'SYS', '2014M09'], 'values': ['4808.7', '35.9']},
 {'key': ['tot15-74', 'SYS', '2014M10'], 'values': ['4771.9', '36.2']},
 {'key': ['tot15-74', 'SYS', '2014M11'], 'values': ['4785.5', '36.9']},
 {'key': ['tot15-74', 'SYS', '2014M12'], 'values': ['4763.1', '35.0']},
 {'key': ['tot15-74', 'SYS', '2015M01'], 'values': ['4716.5', '35.9']},
 {'key': ['tot15-74', 'SYS', '2015M02'], 'values': ['4729.6', '35.8']},
 {'key': ['tot15-74', 'SYS', '2015M03'], 'values': ['4766.8', '36.6']},
 {'key': ['tot15-74', 'SYS', '2015M04'], 'values': ['4761.7', '36.7']},
 {'key': ['tot15-74', 'SYS', '2015M05'], 'values': ['4829.0', '36.8']},
 {'key': ['tot15-74', 'SYS', '2015M06'], 'values': ['4902.6', '37.2']},
 {'key': ['tot15-74', 'SYS', '2015M07'], 'values': ['5002.7', '36.8']},
 {'key': ['tot15-74', 'SYS', '2015M08'], 'values': ['4961.7', '38.2']},
 {'key': ['tot15-74', 'SYS', '2015M09'], 'values': ['4831.8', '37.2']},
 {'key': ['tot15-74', 'SYS', '2015M10'], 'values': ['4853.2', '36.4']},
 {'key': ['tot15-74', 'SYS', '2015M11'], 'values': ['4872.8', '38.2']},
 {'key': ['tot15-74', 'SYS', '2015M12'], 'values': ['4821.0', '36.6']},
 {'key': ['tot15-74', 'SYS', '2016M01'], 'values': ['4790.5', '36.2']},
 {'key': ['tot15-74', 'SYS', '2016M02'], 'values': ['4805.7', '37.6']},
 {'key': ['tot15-74', 'SYS', '2016M03'], 'values': ['4832.5', '37.4']},
 {'key': ['tot15-74', 'SYS', '2016M04'], 'values': ['4872.7', '37.0']},
 {'key': ['tot15-74', 'SYS', '2016M05'], 'values': ['4891.7', '38.5']},
 {'key': ['tot15-74', 'SYS', '2016M06'], 'values': ['5018.1', '38.3']},
 {'key': ['tot15-74', 'SYS', '2016M07'], 'values': ['5058.9', '37.7']},
 {'key': ['tot15-74', 'SYS', '2016M08'], 'values': ['4960.8', '39.2']},
 {'key': ['tot15-74', 'SYS', '2016M09'], 'values': ['4915.6', '37.7']},
 {'key': ['tot15-74', 'SYS', '2016M10'], 'values': ['4929.9', '39.0']},
 {'key': ['tot15-74', 'SYS', '2016M11'], 'values': ['4946.7', '39.6']},
 {'key': ['tot15-74', 'SYS', '2016M12'], 'values': ['4892.8', '36.9']},
 {'key': ['tot15-74', 'SYS', '2017M01'], 'values': ['4880.4', '37.8']},
 {'key': ['tot15-74', 'SYS', '2017M02'], 'values': ['4920.1', '38.9']},
 {'key': ['tot15-74', 'SYS', '2017M03'], 'values': ['4963.0', '37.6']},
 {'key': ['tot15-74', 'SYS', '2017M04'], 'values': ['4965.5', '38.2']},
 {'key': ['tot15-74', 'SYS', '2017M05'], 'values': ['4983.4', '38.9']},
 {'key': ['tot15-74', 'SYS', '2017M06'], 'values': ['5128.9', '38.9']},
 {'key': ['tot15-74', 'SYS', '2017M07'], 'values': ['5163.7', '38.8']},
 {'key': ['tot15-74', 'SYS', '2017M08'], 'values': ['5109.1', '39.9']},
 {'key': ['tot15-74', 'SYS', '2017M09'], 'values': ['5051.8', '39.9']},
 {'key': ['tot15-74', 'SYS', '2017M10'], 'values': ['5041.1', '39.5']},
 {'key': ['tot15-74', 'SYS', '2017M11'], 'values': ['5035.2', '40.6']},
 {'key': ['tot15-74', 'SYS', '2017M12'], 'values': ['5004.5', '39.3']},
 {'key': ['tot15-74', 'SYS', '2018M01'], 'values': ['4968.8', '38.9']},
 {'key': ['tot15-74', 'SYS', '2018M02'], 'values': ['5038.8', '38.8']},
 {'key': ['tot15-74', 'SYS', '2018M03'], 'values': ['5038.3', '39.9']},
 {'key': ['tot15-74', 'SYS', '2018M04'], 'values': ['5043.3', '39.0']},
 {'key': ['tot15-74', 'SYS', '2018M05'], 'values': ['5101.2', '39.3']},
 {'key': ['tot15-74', 'SYS', '2018M06'], 'values': ['5196.5', '40.3']},
 {'key': ['tot15-74', 'SYS', '2018M07'], 'values': ['5271.0', '57.1']},
 {'key': ['tot15-74', 'SYS', '2018M08'], 'values': ['5143.2', '56.2']},
 {'key': ['tot15-74', 'SYS', '2018M09'], 'values': ['5088.8', '58.4']},
 {'key': ['tot15-74', 'SYS', '2018M10'], 'values': ['5095.4', '56.7']},
 {'key': ['tot15-74', 'SYS', '2018M11'], 'values': ['5095.9', '55.5']},
 {'key': ['tot15-74', 'SYS', '2018M12'], 'values': ['5083.2', '54.7']},
 {'key': ['tot15-74', 'SYS', '2019M01'], 'values': ['5020.2', '54.6']},
 {'key': ['tot15-74', 'SYS', '2019M02'], 'values': ['5030.1', '54.9']},
 {'key': ['tot15-74', 'SYS', '2019M03'], 'values': ['5096.2', '56.3']},
 {'key': ['tot15-74', 'SYS', '2019M04'], 'values': ['5104.6', '56.2']},
 {'key': ['tot15-74', 'SYS', '2019M05'], 'values': ['5057.1', '56.2']},
 {'key': ['tot15-74', 'SYS', '2019M06'], 'values': ['5249.0', '57.8']},
 {'key': ['tot15-74', 'SYS', '2019M07'], 'values': ['5269.3', '58.8']},
 {'key': ['tot15-74', 'SYS', '2019M08'], 'values': ['5166.4', '60.5']},
 {'key': ['tot15-74', 'SYS', '2019M09'], 'values': ['5168.1', '60.6']},
 {'key': ['tot15-74', 'SYS', '2019M10'], 'values': ['5138.3', '60.0']},
 {'key': ['tot15-74', 'SYS', '2019M11'], 'values': ['5139.7', '60.3']},
 {'key': ['tot15-74', 'SYS', '2019M12'], 'values': ['5115.3', '59.4']},
 {'key': ['tot15-74', 'SYS', '2020M01'], 'values': ['5034.2', '57.9']},
 {'key': ['tot15-74', 'SYS', '2020M02'], 'values': ['5076.8', '56.1']},
 {'key': ['tot15-74', 'SYS', '2020M03'], 'values': ['5055.4', '55.6']},
 {'key': ['tot15-74', 'SYS', '2020M04'], 'values': ['5005.4', '52.0']},
 {'key': ['tot15-74', 'SYS', '2020M05'], 'values': ['5023.2', '53.7']},
 {'key': ['tot15-74', 'SYS', '2020M06'], 'values': ['5100.8', '53.9']},
 {'key': ['tot15-74', 'SYS', '2020M07'], 'values': ['5149.7', '54.6']},
 {'key': ['tot15-74', 'SYS', '2020M08'], 'values': ['5116.2', '54.8']},
 {'key': ['tot15-74', 'SYS', '2020M09'], 'values': ['5036.1', '55.5']},
 {'key': ['tot15-74', 'SYS', '2020M10'], 'values': ['5062.0', '55.2']},
 {'key': ['tot15-74', 'SYS', '2020M11'], 'values': ['5061.7', '54.2']},
 {'key': ['tot15-74', 'SYS', '2020M12'], 'values': ['5053.5', '55.7']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M01'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M02'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M03'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M04'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M05'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M06'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M07'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M08'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M09'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M10'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M11'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2000M12'], 'values': ['..', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M01'], 'values': ['3639.9', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M02'], 'values': ['3817.3', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M03'], 'values': ['3809.5', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M04'], 'values': ['3789.5', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M05'], 'values': ['3909.7', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M06'], 'values': ['3784.9', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M07'], 'values': ['2272.7', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M08'], 'values': ['3169.0', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M09'], 'values': ['3875.4', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M10'], 'values': ['3896.1', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M11'], 'values': ['3905.1', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2001M12'], 'values': ['3536.0', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2002M01'], 'values': ['3558.0', '..']},
 {'key': ['tot15-74', 'IARBAVSYSS', '2002M02'], 'values': ['3813.9', '..']},

In [15]:
# Create a DataFrame from the extracted data
df = pd.DataFrame(scb_uttag)
df

                                 key          values
0           [tot15-74, SYS, 2000M01]        [.., ..]
1           [tot15-74, SYS, 2000M02]        [.., ..]
2           [tot15-74, SYS, 2000M03]        [.., ..]
3           [tot15-74, SYS, 2000M04]        [.., ..]
4           [tot15-74, SYS, 2000M05]        [.., ..]
..                               ...             ...
499  [tot15-74, IARBAVSYSS, 2020M08]  [3400.9, 72.2]
500  [tot15-74, IARBAVSYSS, 2020M09]  [4560.1, 61.9]
501  [tot15-74, IARBAVSYSS, 2020M10]  [4584.9, 61.2]
502  [tot15-74, IARBAVSYSS, 2020M11]  [4600.8, 59.8]
503  [tot15-74, IARBAVSYSS, 2020M12]  [3992.3, 68.0]

[504 rows x 2 columns]

In [16]:
# Create a new DataFrame from the 'key' column, splitting it into 'Population', 'Info', and 'Dates'
split_df = pd.DataFrame(df['key'].tolist(), columns=['Population', 'Info','Dates'])
split_df

    Population        Info    Dates
0     tot15-74         SYS  2000M01
1     tot15-74         SYS  2000M02
2     tot15-74         SYS  2000M03
3     tot15-74         SYS  2000M04
4     tot15-74         SYS  2000M05
..         ...         ...      ...
499   tot15-74  IARBAVSYSS  2020M08
500   tot15-74  IARBAVSYSS  2020M09
501   tot15-74  IARBAVSYSS  2020M10
502   tot15-74  IARBAVSYSS  2020M11
503   tot15-74  IARBAVSYSS  2020M12

[504 rows x 3 columns]

In [17]:
# Create another DataFrame from the 'values' column
split_df2 = pd.DataFrame(df['values'].tolist(), columns=['Sysselsättning', 'Sysselsättning[%]'])
split_df2

    Sysselsättning Sysselsättning[%]
0               ..                ..
1               ..                ..
2               ..                ..
3               ..                ..
4               ..                ..
..             ...               ...
499         3400.9              72.2
500         4560.1              61.9
501         4584.9              61.2
502         4600.8              59.8
503         3992.3              68.0

[504 rows x 2 columns]

In [18]:
# Concatenate the two DataFrames along columns
df = pd.concat([split_df, split_df2], axis=1)
# display df
df

    Population        Info    Dates Sysselsättning Sysselsättning[%]
0     tot15-74         SYS  2000M01             ..                ..
1     tot15-74         SYS  2000M02             ..                ..
2     tot15-74         SYS  2000M03             ..                ..
3     tot15-74         SYS  2000M04             ..                ..
4     tot15-74         SYS  2000M05             ..                ..
..         ...         ...      ...            ...               ...
499   tot15-74  IARBAVSYSS  2020M08         3400.9              72.2
500   tot15-74  IARBAVSYSS  2020M09         4560.1              61.9
501   tot15-74  IARBAVSYSS  2020M10         4584.9              61.2
502   tot15-74  IARBAVSYSS  2020M11         4600.8              59.8
503   tot15-74  IARBAVSYSS  2020M12         3992.3              68.0

[504 rows x 5 columns]

In [19]:
# Drop unnecessary columns
df.drop(columns=['Population','Info' ], inplace=True)

In [20]:
df

       Dates Sysselsättning Sysselsättning[%]
0    2000M01             ..                ..
1    2000M02             ..                ..
2    2000M03             ..                ..
3    2000M04             ..                ..
4    2000M05             ..                ..
..       ...            ...               ...
499  2020M08         3400.9              72.2
500  2020M09         4560.1              61.9
501  2020M10         4584.9              61.2
502  2020M11         4600.8              59.8
503  2020M12         3992.3              68.0

[504 rows x 3 columns]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 504 entries, 0 to 503
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Dates              504 non-null    object
 1   Sysselsättning     504 non-null    object
 2   Sysselsättning[%]  504 non-null    object
dtypes: object(3)
memory usage: 11.9+ KB

In [22]:
# Extract year and month from the 'Dates' column and add '01' for the day
df['Dates'] = df['Dates'].str.extract('(\d{4})M(\d{2})').apply(lambda x: x[0] + x[1] + '01', axis=1)



# Convert the 'Date' column to datetime format 
df['Dates'] = pd.to_datetime(df['Dates'], format='%Y%m%d')

In [23]:
df

         Dates Sysselsättning Sysselsättning[%]
0   2000-01-01             ..                ..
1   2000-02-01             ..                ..
2   2000-03-01             ..                ..
3   2000-04-01             ..                ..
4   2000-05-01             ..                ..
..         ...            ...               ...
499 2020-08-01         3400.9              72.2
500 2020-09-01         4560.1              61.9
501 2020-10-01         4584.9              61.2
502 2020-11-01         4600.8              59.8
503 2020-12-01         3992.3              68.0

[504 rows x 3 columns]

In [24]:
# Set 'Dates' as the index
df.set_index('Dates', inplace=True)
df

           Sysselsättning Sysselsättning[%]
Dates
2000-01-01             ..                ..
2000-02-01             ..                ..
2000-03-01             ..                ..
2000-04-01             ..                ..
2000-05-01             ..                ..
...                   ...               ...
2020-08-01         3400.9              72.2
2020-09-01         4560.1              61.9
2020-10-01         4584.9              61.2
2020-11-01         4600.8              59.8
2020-12-01         3992.3              68.0

[504 rows x 2 columns]

In [25]:
# Save the DataFrame to an Excel file
df.to_excel('employment.xlsx', index=True)